version: "3.7"

services:
  db:
    image: "mysql:8"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: echo
      MYSQL_ROOT_PASSWORD: 123456
